### ISSUE TITLE
Installing replication-monitor on MacOSX Sierra fails

### ISSUE THREAD

**Issue by bernharduw** [RipcordSoftware/homebrew-packages#1]
I tried to install replication-monitor, but failed with this message from brew:

```bash
Last 15 lines from […]/Library/Logs/Homebrew/replication-monitor/01.python3:
python3
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/tmp/replication-monitor--homebrew-virtualenv-20170222-75226-3l8uls/target
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'
```

Sorry, I'm a total python newbie – do you know what the problem could be?

**Comment by craigminihan** [comment]
@bernharduw I just went back to a clean Sierra and it worked fine.

Did you already have Python installed on your system before installing repl-mon?

**Comment by bernharduw** [comment]
I think so, but I think python came with MacOS. I have this on my system:

````
MacBook-Pro:~$ which python
/usr/bin/python
MacBook-Pro:~$ which python3
/usr/local/bin/python3
MacBook-Pro:~$ python -V
Python 2.7.10
MacBook-Pro:~$ python3 -V
Python 3.6.0
````

python3 was just installed as a dependency during the `brew install replication-monitor` process.

**Comment by craigminihan** [comment]
@bernharduw I've found this issue raised against numpy which looks very similar: Homebrew/homebrew-python#253.

Can you run the command `python3 -c "import setuptools"` from the command prompt to see what that reports?

**Comment by bernharduw** [comment]
```
$ python3 -c "import setuptools"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'
```

I'll also check the issue you linked.

**Comment by bernharduw** [comment]
After `brew postinstall python3` I called `python3 -c "import setuptools"`, and now I don't get an error any more.

Now `brew install ripcordsoftware/packages/replication-monitor` worked! Thanks!

I'm leaving this issue open in case you need to add something to the brew script – feel free to close it.
